### ISSUE TITLE
V/OC POLY is not functional with CV-FDR LINK values other than INDEP.

### ISSUE THREAD

**Issue by tfleig** [Befaco/VCMC#11]
I fixed this by changing these lines in InputControl.ino:

Line 190:
` if (CVPort.PortCfg.MIDIfunction == TRIGGER) {`
to
` if (CVPort.PortCfg.MIDIfunction == TRIGGER || CVPort.PortCfg.MIDIfunction == PITCH8TRIG) {`

and 

Line 242:
 `if (CVPort.PortCfg.MIDIfunction == TRIGGER) {`
to
`if (CVPort.PortCfg.MIDIfunction == TRIGGER || CVPort.PortCfg.MIDIfunction == PITCH8TRIG) {`

I hope this change can be included in future updates.

**Comment by SergioRetamero** [comment]
Thanks a lot, wonderful issue report.
Updated on Development branch for testing.

**Comment by SergioRetamero** [comment]
Included on version 1.2.3
