### ISSUE TITLE
Gate button suggestions

### ISSUE THREAD

**Issue by cowboy** [Befaco/VCMC#3]
Love VCMC! I have a few gate button suggestions

1. Allow gate buttons to be decoupled from corresponding gate input
1. Allow gate buttons to toggle (momentary / latch) the corresponding fader to a second function / midi channel / range

**Comment by xustafu** [comment]
1. Not possible as they are bound by hardware.
2. Mapping control to internal functions will be implemented i nthe future. This could be a cool feature!

**Comment by cowboy** [comment]
> Mapping control to internal functions will be implemented i nthe future. This could be a cool feature!

Awesome! I can't wait!

**Comment by xustafu** [comment]
This feature is in the wishlist for v1.2
Closing the issue as its a new feature request.
