### ISSUE TITLE
Channel CV Calibration / In Range resetting each other

### ISSUE THREAD

**Issue by cowboy** [Befaco/VCMC#4]
I'm on fw v1.0.1, and I've noticed the following issues:

1. When I calibrate a Channel CV it resets the In Range to +10
1. When I change a Channel In Range to +5 it resets the CV calibration

(I have only tried this with Channel 1/2 CV)

To start, these are the settings I need for my MIDI device, so I do:

- Channel 1
  - CV
    - Function → CC → 004
    - MIDI Channel → 16
  - Ranges
    - In Range → +5

And this is what I see on the screen when I supply a voltage:

- Input 0V → CV 0
- Input 5V → CV 112

So, I calibrate using a reliable voltage source:

- Channel 1
  - Ranges
    - Calibration
      - Set 1V with 1V source (showed 0.91V before calibration, now shows 1V)
      - Set 4V with 4V source (showed 6.86V before calibration, now shows 4V)

This is what I expect to see:
- Input 0V → CV 0
- Input 5V → CV 127

But this is what I actually see:
- Input 0V → CV 0
- Input 5V → CV 63
- Input 10V → CV 127

It appears that calibrating has reset In Range to +10, so I set it to +5:

- Channel 1
  - Ranges
    - In Range → +5

And now I see the pre-calibration values again:

- Input 0V → CV 0
- Input 5V → CV 112

So, I go back to the calibration screen, and see the pre-calibration voltages:

- Channel 1
  - Ranges
    - Calibration
      - 1V source shows 0.91V again
      - 4V source shows 6.86V again

**Comment by cowboy** [comment]
I'm happy to beta test any fix, just LMK

**Comment by xustafu** [comment]
Managed to reproduce this issue. It is a bug that will be solved in version 1.1
Please contact us via mail and request 16 May Beta version to test.

**Comment by xustafu** [comment]
Fixed in current version!
