### ISSUE TITLE
Global config option to change encoder direction

### ISSUE THREAD

**Issue by toneburst** [Befaco/VCMC#5]
Would be cool to add a global option to reverse encoder direction, in case using different encoder type.

**Comment by SergioRetamero** [comment]
Since this is a "hard wired" situation you might just change the pins on the file Definitions.h for the encoder, i.e.:
Change these pins 
const uint8_t PINENCA = 7;
const uint8_t PINENCB = 6;
to this values
const uint8_t PINENCA = 6;
const uint8_t PINENCB = 7;

**Comment by toneburst** [comment]
OK, thanks, I will try that. It would still be handy to have a config option too, though, I think.

**Comment by SergioRetamero** [comment]
I will include it to the wish list for v1.2

Thanks a lot for the feedback!
