### ISSUE TITLE
Screen glitches with both precompiled 1.2 CV Thing hex files

### ISSUE THREAD

**Issue by JuhoKosunen** [Befaco/VCMC#7]
Lowest part of the screen folds to the top of the screen on both versions of the hex files (00 and ff). Previously the V1_1_Jul_0x01.hex resulted in correctly working screen while V1_1_Jul_0x00.hex produced similar (faulty) results.

**Comment by xustafu** [comment]
Screens are not consistent between batches, so a tweak need to be done on the code (see Reame.md) 
Just added a third compiled binary, please check if that works.

**Comment by JuhoKosunen** [comment]
Hi, can confirm that the third compiled binary CV_THING_1_2_01.hex works on my hardware, screen is now as it should be. Thanks for the quick fix!
